import nodemailer from "nodemailer";
import type { Report } from "./types";
import { DEPARTMENT_EMAIL } from "./constants";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: process.env.GMAIL_USER,
    pass: process.env.GMAIL_APP_PASSWORD,
  },
});

function getPriorityLabel(priority: string): string {
  const labels: Record<string, string> = {
    critical: "🔴 CRITICAL",
    high: "🟠 HIGH",
    medium: "🟡 MEDIUM",
    low: "🟢 LOW",
  };
  return labels[priority] ?? priority.toUpperCase();
}

function buildEmailHtml(report: Report): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; color: #333; max-width: 600px; margin: 0 auto; }
    .header { background: #00539F; color: white; padding: 20px; border-radius: 8px 8px 0 0; }
    .header h1 { margin: 0; font-size: 22px; }
    .header p { margin: 4px 0 0; font-size: 14px; opacity: 0.85; }
    .body { padding: 20px; border: 1px solid #ddd; border-top: none; border-radius: 0 0 8px 8px; }
    .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: bold; }
    .critical { background: #fee2e2; color: #991b1b; }
    .high { background: #ffedd5; color: #9a3412; }
    .medium { background: #fef9c3; color: #854d0e; }
    .low { background: #dcfce7; color: #166534; }
    .field { margin: 12px 0; }
    .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .value { font-size: 15px; margin-top: 2px; }
    .divider { border: none; border-top: 1px solid #eee; margin: 16px 0; }
    .footer { font-size: 12px; color: #999; margin-top: 16px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>FixIt AI — New Work Order</h1>
    <p>University of Delaware Facilities Management</p>
  </div>
  <div class="body">
    <div class="field">
      <div class="label">Priority</div>
      <div class="value">
        <span class="badge ${report.priority}">${getPriorityLabel(report.priority)}</span>
        ${report.safety_concern ? '<span style="margin-left:8px;color:#dc2626;font-weight:bold;">⚠️ Safety Concern</span>' : ""}
      </div>
    </div>

    <hr class="divider" />

    <div class="field">
      <div class="label">Location</div>
      <div class="value">${report.building}${report.floor ? `, Floor ${report.floor}` : ""}${report.room ? `, Room ${report.room}` : ""}</div>
    </div>

    <div class="field">
      <div class="label">Trade</div>
      <div class="value">${report.trade.charAt(0).toUpperCase() + report.trade.slice(1).replace("_", " ")}</div>
    </div>

    <div class="field">
      <div class="label">AI Description</div>
      <div class="value">${report.ai_description}</div>
    </div>

    <div class="field">
      <div class="label">Suggested Action</div>
      <div class="value">${report.suggested_action}</div>
    </div>

    <div class="field">
      <div class="label">Reporter Description</div>
      <div class="value">${report.description || "None provided"}</div>
    </div>

    <hr class="divider" />

    <div class="field">
      <div class="label">Estimated Cost</div>
      <div class="value">${report.estimated_cost}</div>
    </div>

    <div class="field">
      <div class="label">Estimated Repair Time</div>
      <div class="value">${report.estimated_time}</div>
    </div>

    <div class="field">
      <div class="label">AI Confidence</div>
      <div class="value">${Math.round(report.confidence_score * 100)}%</div>
    </div>

    ${
      report.reporter_name || report.reporter_email
        ? `
    <hr class="divider" />
    <div class="field">
      <div class="label">Reported By</div>
      <div class="value">${report.reporter_name || ""}${report.reporter_email ? ` &lt;${report.reporter_email}&gt;` : ""}</div>
    </div>`
        : ""
    }

    <hr class="divider" />
    <div class="field">
      <div class="label">Report ID</div>
      <div class="value" style="font-family:monospace;font-size:13px;">${report.id}</div>
    </div>
    <div class="field">
      <div class="label">Submitted At</div>
      <div class="value">${new Date(report.created_at).toLocaleString("en-US", { timeZone: "America/New_York" })} ET</div>
    </div>

    <div class="footer">
      This work order was automatically generated by FixIt AI. Powered by OpenAI Vision + UDel Facilities.
    </div>
  </div>
</body>
</html>`;
}

export async function sendDispatchEmail(report: Report): Promise<void> {
  const to = DEPARTMENT_EMAIL[report.trade];
  const priorityLabel = getPriorityLabel(report.priority);

  await transporter.sendMail({
    from: `"FixIt AI — UDel Facilities" <${process.env.GMAIL_USER}>`,
    to,
    subject: `[${priorityLabel}] ${report.trade.replace("_", " ").toUpperCase()} issue at ${report.building} — Work Order #${report.id.slice(0, 8)}`,
    html: buildEmailHtml(report),
  });
}
